# Site settings
title: Eroica.io
email: gnu.seba@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Developer & designer in Germany and Taiwan.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eroica.io" # the base hostname & protocol for your site
twitter_username: MyEroica
github_username:  Eroica

# Build settings
markdown: kramdown

sass:
  style: :compressed

exclude:
  - "feed.xml"