# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: (Hi!) Eroica — Android & Lua Developer
description: > # this means to ignore newlines until "baseurl:"
  Hi! I’m an Android & Lua developer. Currently doing freelance work focusing on Android & web apps and UI design.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://eroica.io" # the base hostname & protocol for your site
twitter_username: MyEroica
github_username: Eroica

github-url: https://github.com/Eroica
medium-url: https://medium.com/@eroica
twitter-url: https://twitter.com/MyEroica
tumblr-url: https://eroicaio.tumblr.com
dribbble-url: https://dribbble.com/Eroica

# Build settings
markdown: kramdown
